void modified_data_types();
void derived_data_types();
void pointers_in_c();
void functions_in_c();
void void_functions();
void void_pointers();
void structures_in_c();
void unions_in_c();
void enumerations_in_c();